version: '3.4'

services:
  api:
    depends_on:
      - mock-oauth2-server
    environment:
      - AUTHORITY=http://mock-oauth2-server:8080/default
      - AUDIENCE=default
  tests:
    build: ./tests
    depends_on:
      - api
      - mock-oauth2-server
    environment:
      - API_ADDR=http://api:8000
      - AUTHORITY=http://mock-oauth2-server:8080/default
      - CLIENT_ID=default
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.4
    environment:
      - JSON_CONFIG={"interactiveLogin":false}
