version: '3.7'

services:
  api:
    build:
      context: api
    depends_on:
      - mock-oauth2-server
      - az
    environment:
      - AUTHORITY=http://mock-oauth2-server:8080/default
      - AUDIENCE=default
      - STORAGE_URL=https://az:10000/devstoreaccount1
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/az.pem
    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
  tests:
    build: ./tests
    depends_on:
      - api
      - mock-oauth2-server
    environment:
      - API_ADDR=http://api:8000
      - AUTHORITY=http://mock-oauth2-server:8080/default
      - CLIENT_ID=default
  az:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite-blob --blobHost 0.0.0.0 --oauth basic --loose --cert /tests/ssl/az.pem --key /tests/ssl/key.pem
    volumes:
      - ./tests/ssl:/tests/ssl
    ports:
      - 10000:10000
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.4
    environment:
      - JSON_CONFIG={"interactiveLogin":false,"httpServer":"MockWebServerWrapper","tokenCallbacks":[{"issuerId":"default","requestMappings":[{"requestParam":"scope","match":"https://storage.azure.com/user_impersonation","claims":{"sub":"https://sts.windows.net/","aud":["https://storage.azure.com"],"iss":"https://sts.windows.net/"}}]}]}
